# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  reverse-proxy:
    image: traefik:v3.2
    command: --providers.docker
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  frontend:
    build:
      context: .
      target: dev
    environment:
      - TZ=Asia/Shanghai
    volumes:
      #      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.http.routers.frontend.rule: "Host(`localhost`)"
      traefik.http.services.frontend.loadbalancer.server.port: 80

  backend:
    image: ruoyi-vue-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      #      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.http.routers.backend.rule: "Host(`localhost`) && PathPrefix(`/dev-api`)"
      traefik.http.services.backend.loadbalancer.server.port: 8080
